language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"

install:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -q Pillow wheezy.captcha; fi

script:
    - python setup.py -q nosetests

after_success:
    - pip install coveralls
    - coverage run --source=captcha setup.py -q nosetests
    - coveralls

notifications:
    email: false
